Repository zilliztech/deep-searcher, pull requests merged in 2025-03, with the labels that each got.

#100 robust LLM output parser for some corner cases
  deepsearcher/agent/rag_router.py
  deepsearcher/llm/base.py
Labels: approved, lgtm, size/S

#98 Master
  tests/test_milvus.py
Labels: approved, lgtm, size/S

#102 Update README.md
  README.md
Labels: approved, lgtm, size/XS

#103 refactor publish config to use uv
  .python-version
  LICENSE
  deepsearcher/config.yaml
  deepsearcher/configuration.py
  pyproject.toml
  requirements-dev.txt
  requirements.txt
  setup.py
  uv.lock
Labels: approved, size/XXL

#105 Enhance Crawl4AI integration
  README.md
  config.yaml
  deepsearcher/loader/web_crawler/base.py
  deepsearcher/loader/web_crawler/crawl4ai_crawler.py
  deepsearcher/offline_loading.py
Labels: approved, size/M, lgtm

#111 Print final answer and references to CLI output
  deepsearcher/cli.py
Labels: approved, lgtm, size/XS

#112 refactor: modify critical log to always raise RuntimeError
  deepsearcher/tools/log.py
Labels: approved, lgtm, size/XS

#109 enhance: add optional dependencies using uv
  pyproject.toml
Labels: approved, size/M, lgtm

#115 backward compatibility of dynamic iter_num
  deepsearcher/agent/chain_of_rag.py
  deepsearcher/agent/deep_search.py
  deepsearcher/cli.py
  deepsearcher/online_query.py
Labels: approved, lgtm, size/S

#116 Support batch embedding in SiliconflowEmbedding
  deepsearcher/embedding/siliconflow_embedding.py
  deepsearcher/embedding/voyage_embedding.py
Labels: approved, size/M, lgtm

#117 Print final answers to the console in ChainOfRAG, DeepSearch, and NaiveRAG agents
  deepsearcher/agent/chain_of_rag.py
  deepsearcher/agent/deep_search.py
Labels: approved, lgtm, size/XS

#118 post eval result
  evaluation/README.md
  evaluation/plot_results/LLM_vs_recall.png
  evaluation/plot_results/max_iter_vs_recall.png
  evaluation/plot_results/max_iter_vs_token_usage.png
Labels: approved, lgtm, size/S

#124 refactor: enhance CLI with subcommand using subparsers
  README.md
  deepsearcher/cli.py
  deepsearcher/vector_db/oracle.py
Labels: approved, lgtm, size/L

#126 optimize the relative path of the examples
  examples/basic_example.py
  examples/basic_example_oracle.py
Labels: approved, lgtm, size/S

#129 add badges
  README.md
Labels: approved, lgtm, size/XS

#133 add qwq as default ollama model
  README.md
  config.yaml
  deepsearcher/llm/ollama.py
  evaluation/eval_config.yaml
Labels: approved, lgtm, size/S

#135 add max_iter arg in evaluate script
  evaluation/evaluate.py
Labels: approved, lgtm, size/S

#137 add more info in evaluation stats
  evaluation/evaluate.py
Labels: approved, lgtm, size/S

#138 feat: add CORS support configuration to FastAPI server
  main.py
Labels: approved, lgtm, size/S

#139 feat: add endpoint to set provider configuration
  main.py
Labels: approved, lgtm, size/S

#136 feat: add a parameter for batch size when loading files or websites
  deepsearcher/cli.py
  deepsearcher/embedding/base.py
  deepsearcher/offline_loading.py
  main.py
Labels: approved, size/M, lgtm

#130 fix oracle to store collection description
  deepsearcher/vector_db/oracle.py
Labels: approved, size/M, lgtm

#140 docs: add example for setting provider configuration in README
  README.md
Labels: approved, lgtm, size/XS

#143 Added support for Gemini text embedding models
  config.yaml
  deepsearcher/embedding/__init__.py
  deepsearcher/embedding/gemini_embedding.py
Labels: approved, size/M, lgtm

#145 add docstr
  deepsearcher/agent/base.py
  deepsearcher/agent/chain_of_rag.py
  deepsearcher/agent/collection_router.py
  deepsearcher/agent/deep_search.py
  deepsearcher/agent/naive_rag.py
  deepsearcher/agent/rag_router.py
  deepsearcher/cli.py
  deepsearcher/configuration.py
  deepsearcher/embedding/base.py
  deepsearcher/embedding/bedrock_embedding.py
  deepsearcher/embedding/gemini_embedding.py
  deepsearcher/embedding/milvus_embedding.py
  deepsearcher/embedding/openai_embedding.py
  deepsearcher/embedding/siliconflow_embedding.py
  deepsearcher/embedding/voyage_embedding.py
  deepsearcher/llm/anthropic_llm.py
  deepsearcher/llm/azure_openai.py
  deepsearcher/llm/base.py
  deepsearcher/llm/deepseek.py
  deepsearcher/llm/gemini.py
  deepsearcher/llm/ollama.py
  deepsearcher/llm/openai_llm.py
  deepsearcher/llm/ppio.py
  deepsearcher/llm/siliconflow.py
  deepsearcher/llm/together_ai.py
  deepsearcher/llm/xai.py
  deepsearcher/loader/file_loader/base.py
  deepsearcher/loader/file_loader/json_loader.py
  deepsearcher/loader/file_loader/pdf_loader.py
  deepsearcher/loader/file_loader/text_loader.py
  deepsearcher/loader/file_loader/unstructured_loader.py
  deepsearcher/loader/splitter.py
  deepsearcher/loader/web_crawler/base.py
  deepsearcher/loader/web_crawler/crawl4ai_crawler.py
  deepsearcher/loader/web_crawler/firecrawl_crawler.py
  deepsearcher/loader/web_crawler/jina_crawler.py
  deepsearcher/offline_loading.py
  deepsearcher/online_query.py
  deepsearcher/tools/log.py
  deepsearcher/vector_db/base.py
  deepsearcher/vector_db/milvus.py
  deepsearcher/vector_db/oracle.py
  evaluation/evaluate.py
  main.py
Labels: approved, lgtm, size/XXL

#147 add early stopping option for chain of rag
  deepsearcher/agent/chain_of_rag.py
Labels: approved, size/M, lgtm

#149 Add Volcengine for llm and embeddings
  README.md
  deepsearcher/embedding/__init__.py
  deepsearcher/embedding/volcengine_embedding.py
  deepsearcher/llm/__init__.py
  deepsearcher/llm/volcengine.py
Labels: approved, lgtm, size/L

#148 Add PPIO embedding
  README.md
  config.yaml
  deepsearcher/embedding/__init__.py
  deepsearcher/embedding/ppio_embedding.py
  deepsearcher/llm/ppio.py
  evaluation/eval_config.yaml
Labels: approved, lgtm, size/L

#152 fix the issue of collection router
  deepsearcher/agent/chain_of_rag.py
  deepsearcher/agent/deep_search.py
Labels: approved, lgtm, size/XS

#156 Add dimension parameter to CollectionRouter and update invocations
  deepsearcher/agent/chain_of_rag.py
  deepsearcher/agent/collection_router.py
  deepsearcher/agent/deep_search.py
  deepsearcher/agent/naive_rag.py
  deepsearcher/vector_db/milvus.py
Labels: approved, size/M, lgtm

#159 Add a Gemini embedding example in the README and reset the batch size for embed_chunks.
  README.md
  deepsearcher/embedding/gemini_embedding.py
Labels: approved, lgtm, size/S

#157 fix the early stopping logic and support GLM_API
  README.md
  deepsearcher/agent/chain_of_rag.py
  deepsearcher/embedding/__init__.py
  deepsearcher/embedding/glm_embedding.py
  deepsearcher/llm/__init__.py
  deepsearcher/llm/glm.py
Labels: approved, lgtm, size/L

#161 update ZhipuAI support
  README.md
  deepsearcher/embedding/glm_embedding.py
  deepsearcher/llm/glm.py
Labels: approved, size/M, lgtm

#166 Improve the robustness of LLM generated indexes.
  deepsearcher/agent/chain_of_rag.py
Labels: approved, lgtm, size/XS

#168 feat: updated volcengine embeddings.
  deepsearcher/embedding/volcengine_embedding.py
Labels: approved, lgtm, size/S

#171 feat: FastEmbed Embeddings
  config.yaml
  deepsearcher/embedding/__init__.py
  deepsearcher/embedding/fastembed_embdding.py
  tests/test_fastembed.py
Labels: approved, lgtm, size/L

#170 feat: Qdrant support
  README.md
  config.yaml
  deepsearcher/vector_db/__init__.py
  deepsearcher/vector_db/qdrant.py
  tests/test_qdrant.py
Labels: approved, lgtm, size/L

#172 feat: Add aws bedrock for llm
  deepsearcher/llm/__init__.py
  deepsearcher/llm/bedrock.py
Labels: approved, size/M, lgtm

#174 docs: add amazon bedrock llm to readme
  README.md
Labels: approved, lgtm, size/XS

#173 feat: add PPIO embedding example in README
  README.md
Labels: approved, lgtm, size/S

#176 feat: allow the region name could be set by user in bedrock embedding
  deepsearcher/embedding/bedrock_embedding.py
Labels: approved, lgtm, size/XS

#181 fix: add batch size parameter to OllamaEmbedding initialization
  README.md
  deepsearcher/embedding/ollama_embedding.py
Labels: approved, lgtm, size/XS

#183 fix: updated firecrawl tutorial with max_depth as param
  examples/load_website_using_firecrawl.py
Labels: approved, lgtm, size/XS
