Repository zilliztech/deep-searcher, pull requests merged in 2025-04, with the labels that each got.

#184 simplify CONTRIBUTING.md
  CONTRIBUTING.md
Labels: approved, lgtm, size/L

#185 update evaluation README.md
  evaluation/README.md
  evaluation/plot_results/LLM_vs_recall.png
  evaluation/plot_results/max_iter_vs_avg_token_usage.png
  evaluation/plot_results/max_iter_vs_error_num.png
  evaluation/plot_results/max_iter_vs_recall.png
  evaluation/plot_results/max_iter_vs_token_usage.png
Labels: approved, lgtm, size/S

#188 add llama 4 example
  README.md
Labels: approved, lgtm, size/XS

#189 support pypi publish
  .github/workflows/release.yml
  .python-version
  CONTRIBUTING.md
  LICENSE
  README.md
  deepsearcher/config.yaml
  deepsearcher/configuration.py
  pyproject.toml
  requirements-dev.txt
  requirements.txt
  setup.py
  uv.lock
Labels: approved, lgtm, size/XXL

#192 refactor name of subpackage from tools to utils
  deepsearcher/agent/chain_of_rag.py
  deepsearcher/agent/collection_router.py
  deepsearcher/agent/deep_search.py
  deepsearcher/agent/naive_rag.py
  deepsearcher/agent/rag_router.py
  deepsearcher/cli.py
  deepsearcher/loader/file_loader/unstructured_loader.py
  deepsearcher/loader/web_crawler/crawl4ai_crawler.py
  deepsearcher/utils/__init__.py
  deepsearcher/utils/log.py
  deepsearcher/vector_db/milvus.py
  deepsearcher/vector_db/oracle.py
  deepsearcher/vector_db/qdrant.py
  tests/test_log.py
  tests/test_milvus.py
  tests/test_prompt.py
Labels: approved, lgtm, size/S

#193 v0.0.1
  pyproject.toml
  uv.lock
Labels: approved, lgtm, size/XS

#194 refine installation docs and ruff workflow
  .github/workflows/ruff.yml
  CONTRIBUTING.md
  Makefile
  README.md
Labels: approved, size/M, lgtm

#195 Add new LLM and embedding model provider Novita AI
  README.md
  deepsearcher/config.yaml
  deepsearcher/embedding/__init__.py
  deepsearcher/embedding/novita_embedding.py
  deepsearcher/llm/__init__.py
  deepsearcher/llm/novita.py
  evaluation/eval_config.yaml
Labels: approved, lgtm, size/L

#199 chore(docs): add aliyun bailian llm api to readme
  README.md
Labels: approved, lgtm, size/XS

#201 add logo to readme
  README.md
  assets/pic/logo.png
Labels: approved, lgtm, size/XS

#202 Feat: add Aliyun llm
  README.md
  deepsearcher/llm/__init__.py
  deepsearcher/llm/aliyun.py
Labels: approved, size/M, lgtm

#203 feat: added docling support for local file loading and web crawling, fix: updated unstructured pipeline with or without api
  README.md
  deepsearcher/config.yaml
  deepsearcher/loader/file_loader/__init__.py
  deepsearcher/loader/file_loader/docling_loader.py
  deepsearcher/loader/file_loader/unstructured_loader.py
  deepsearcher/loader/web_crawler/__init__.py
  deepsearcher/loader/web_crawler/docling_crawler.py
  examples/load_and_crawl_using_docling.py
  examples/load_local_file_using_unstructured.py
  pyproject.toml
  uv.lock
Labels: approved, lgtm, size/XXL

#208 Update pdf_loader.py to use utf8 encoding
  deepsearcher/loader/file_loader/pdf_loader.py
Labels: approved, lgtm, size/XS

#210 Update load_from_website() to include chunk_size and chunk_overlap
  deepsearcher/offline_loading.py
Labels: approved, lgtm, size/S

#209 Update text_loader.py to use utf-8 encoding
  deepsearcher/loader/file_loader/text_loader.py
Labels: approved, lgtm, size/XS

#212 fix(FireCrawlCrawler): adapt to Firecrawl v1+ API signature and Pydantic responses
  deepsearcher/loader/web_crawler/firecrawl_crawler.py
Labels: approved, lgtm, size/S

#214 add print line in example
  examples/load_and_crawl_using_docling.py
  examples/load_local_file_using_unstructured.py
  examples/load_website_using_firecrawl.py
Labels: approved, lgtm, size/XS

#213 fix(FireCrawlCrawler): replace deprecated dict() calls with model_dump() for safety and Pydantic V2 support
  deepsearcher/loader/web_crawler/firecrawl_crawler.py
Labels: approved, size/M, lgtm

#211 Azure Search Vector DB and Azure Open AI Fixes for embeddings.
  README.md
  deepsearcher/embedding/openai_embedding.py
  deepsearcher/vector_db/__init__.py
  deepsearcher/vector_db/azure_search.py
  examples/basic_example_azuresearch.py
Labels: approved, lgtm, size/L

#215 fix issue that <think> tag is mixed in the agent's middle output
  deepsearcher/agent/chain_of_rag.py
  deepsearcher/agent/deep_search.py
  deepsearcher/agent/rag_router.py
  deepsearcher/llm/base.py
Labels: approved, size/M, lgtm

#216 fix dependencies problem
  deepsearcher/vector_db/azure_search.py
  pyproject.toml
  uv.lock
Labels: approved, size/M, lgtm

#218 add qwen3 introduction
  README.md
Labels: approved, size/M, lgtm
