Repository zilliztech/deep-searcher, pull requests merged in 2025-05, with the labels that each got.

#224 fix: deepsearcher dependency issue
  pyproject.toml
  uv.lock
Labels: approved, lgtm, size/XXL

#219 feat: using mkdocs to deploy website via Github Pages; adding ci/cd automated scripts for deployment
  .github/workflows/cd-docs.yml
  .github/workflows/ci-docs.yml
  .github/workflows/docs.yml
  docs/README.md
  docs/assets/pic/deep-searcher-arch.png
  docs/assets/pic/demo.gif
  docs/assets/pic/logo-badge.png
  docs/assets/pic/logo.png
  docs/configuration/embedding.md
  docs/configuration/file_loader.md
  docs/configuration/index.md
  docs/configuration/llm.md
  docs/configuration/vector_db.md
  docs/configuration/web_crawler.md
  docs/examples/basic_example.md
  docs/examples/docling.md
  docs/examples/firecrawl.md
  docs/examples/index.md
  docs/examples/oracle.md
  docs/examples/unstructured.md
  docs/faq/index.md
  docs/future_plans.md
  docs/index.md
  docs/installation/development.md
  docs/installation/index.md
  docs/installation/pip.md
  docs/integrations/index.md
  docs/overrides/.gitkeep
  docs/stylesheets/extra.css
  docs/usage/cli.md
  docs/usage/deployment.md
  docs/usage/index.md
  docs/usage/quick_start.md
  mkdocs.yml
  pyproject.toml
  uv.lock
Labels: approved, lgtm, size/XXL

#225 finalizing deepsearcher website deployment
  docs/index.md
Labels: approved, lgtm, size/XS

#226 Fix: Pass headers correctly to Ollama Client to prevent 401 Unauthorized errors
  README.md
  deepsearcher/embedding/ollama_embedding.py
Labels: approved, lgtm, size/XS

#227 feat: add sentence transformer embedding support.
  deepsearcher/config.yaml
  deepsearcher/embedding/__init__.py
  deepsearcher/embedding/sentence_transformer_embedding.py
  docs/configuration/embedding.md
  pyproject.toml
  uv.lock
Labels: approved, lgtm, size/L

#229 Load files recursively
  deepsearcher/loader/file_loader/base.py
Labels: approved, lgtm, size/S

#230 feat: added milvus hybrid search capability
  deepsearcher/agent/chain_of_rag.py
  deepsearcher/agent/deep_search.py
  deepsearcher/agent/naive_rag.py
  deepsearcher/vector_db/milvus.py
Labels: approved, size/M, lgtm

#231 v0.0.2
  pyproject.toml
  uv.lock
Labels: approved, lgtm, size/XS

#235 support claude 4 sonnet
  README.md
  deepsearcher/llm/anthropic_llm.py
  docs/configuration/llm.md
  docs/index.md
Labels: approved, lgtm, size/S

#242 Adding support for IBM watsonx.ai
  README.md
  deepsearcher/embedding/__init__.py
  deepsearcher/embedding/watsonx_embedding.py
  deepsearcher/llm/__init__.py
  deepsearcher/llm/watsonx.py
  docs/configuration/embedding.md
  docs/configuration/llm.md
  docs/integrations/index.md
  examples/basic_watsonx_example.py
  pyproject.toml
  tests/embedding/test_watsonx_embedding.py
  tests/llm/test_watsonx.py
Labels: approved, lgtm, size/XXL

#244 Add support for other Milvus connection parameters
  README.md
  deepsearcher/vector_db/milvus.py
  docs/configuration/vector_db.md
Labels: approved, lgtm, size/S
