Repository zilliztech/deep-searcher, pull requests merged in 2025-02, with the labels that each got.

#24 fix milvus search data return NoneType, fix unstructured loader when the directory with result does not exist, update README Configuration with VectorDB, FileLoader, WebCrawler, adding examples for loading local file and website
  README.md
  deepsearcher/loader/file_loader/unstructured_loader.py
  deepsearcher/vector_db/milvus.py
  examples/load_local_file_using_unstructured.py
  examples/load_website_using_firecrawl.py
Labels: approved

#32 Fix client initialization order and update model parameter handling
  deepsearcher/embedding/openai_embedding.py
Labels: approved, lgtm, size/XS

#33 add sbert dependency
  requirements.txt
  setup.py
Labels: approved, lgtm, size/XS

#35 Refactor vector DB search prompt to use collection info objects and suppress warnings in environment
  deepsearcher/__init__.py
  deepsearcher/agent/prompt.py
  deepsearcher/agent/search_vdb.py
  tests/test_prompt.py
Labels: approved, size/M, lgtm

#36 add batch size param in milvus insert function
  deepsearcher/vector_db/milvus.py
Labels: approved, lgtm, size/S

#37 feat: support deployment using FastAPI
  README.md
  config.py
  main.py
  requirements.txt
  setup.py
Labels: approved, size/M, lgtm

#38 Update README to correct directory navigation for virtual environment setup
  README.md
Labels: approved, lgtm, size/XS

#41 Added support for Amazon Bedrock embeddings.
  deepsearcher/embedding/__init__.py
  deepsearcher/embedding/bedrock_embedding.py
  deepsearcher/online_query.py
  requirements.txt
Labels: approved, size/M, lgtm

#47 fix: import boto3 in BedrockEmbedding and update example formatting
  deepsearcher/embedding/bedrock_embedding.py
  examples/basic_example.py
  requirements.txt
Labels: approved, lgtm, size/S

#48 docs: update README with installation instructions for dependencies and add Amazon Bedrock embedding example
  README.md
Labels: approved, lgtm, size/S

#46 enhance: add request parameter annotations, add YAML file for configuration
  README.md
  config.py
  config.yaml
  deepsearcher/configuration.py
  main.py
Labels: approved, lgtm, size/L

#49 feat: add support for Google Gemini LLM and update README with usage example
  README.md
  deepsearcher/llm/__init__.py
  deepsearcher/llm/gemini.py
Labels: approved, size/M, lgtm

#51 refactor: update type hints to use Union
  README.md
  deepsearcher/offline_loading.py
  deepsearcher/vector_db/base.py
  deepsearcher/vector_db/milvus.py
  main.py
Labels: approved, size/M, lgtm

#52 chore: specify required Python version in setup.py
  README.md
  setup.py
Labels: approved, lgtm, size/XS

#54 docs: update README with troubleshooting steps for Hugging Face access issues and Jupyter notebook compatibility
  README.md
Labels: approved, lgtm, size/S

#55 Update LLM list
  README.md
Labels: approved, lgtm, size/S

#56 docs: update README to correct Gemini documentation link and add Amazon Bedrock support
  README.md
Labels: approved, lgtm, size/XS

#59 fix config yaml relative path issue
  deepsearcher/configuration.py
Labels: approved, lgtm, size/XS

#60 fix declaration bug
  deepsearcher/online_query.py
Labels: approved, lgtm, size/XS

#62 refined firecrawl_crawler to support crawling multiple links
  deepsearcher/loader/web_crawler/base.py
  deepsearcher/loader/web_crawler/firecrawl_crawler.py
  deepsearcher/offline_loading.py
  examples/load_website_using_firecrawl.py
Labels: approved, size/M, lgtm

#65 feat: enhance files loading in cli mode
  README.md
  deepsearcher/cli.py
Labels: approved, size/M, lgtm

#64 feat: Support Jina embedding model and alternative API key for JinaCrawler
  README.md
  deepsearcher/embedding/milvus_embedding.py
  deepsearcher/loader/web_crawler/jina_crawler.py
Labels: approved, lgtm, size/S

#69 feat: Add support for Siliconflow embedding model and update documentation
  README.md
  config.yaml
  deepsearcher/embedding/__init__.py
  deepsearcher/embedding/siliconflow_embedding.py
  deepsearcher/embedding/voyage_embedding.py
Labels: approved, size/M, lgtm

#70 feat: add Ruff as Python linter and code formatter
  Makefile
  deepsearcher/__init__.py
  deepsearcher/agent/__init__.py
  deepsearcher/agent/prompt.py
  deepsearcher/agent/reflection.py
  deepsearcher/agent/search_vdb.py
  deepsearcher/agent/sub_query.py
  deepsearcher/agent/summay.py
  deepsearcher/cli.py
  deepsearcher/configuration.py
  deepsearcher/embedding/__init__.py
  deepsearcher/embedding/base.py
  deepsearcher/embedding/bedrock_embedding.py
  deepsearcher/embedding/milvus_embedding.py
  deepsearcher/embedding/openai_embedding.py
  deepsearcher/embedding/siliconflow_embedding.py
  deepsearcher/embedding/voyage_embedding.py
  deepsearcher/llm/__init__.py
  deepsearcher/llm/azure_openai.py
  deepsearcher/llm/base.py
  deepsearcher/llm/deepseek.py
  deepsearcher/llm/gemini.py
  deepsearcher/llm/grok.py
  deepsearcher/llm/openai_llm.py
  deepsearcher/llm/siliconflow.py
  deepsearcher/llm/together_ai.py
  deepsearcher/loader/file_loader/__init__.py
  deepsearcher/loader/file_loader/base.py
  deepsearcher/loader/file_loader/json_loader.py
  deepsearcher/loader/file_loader/pdf_loader.py
  deepsearcher/loader/file_loader/text_loader.py
  deepsearcher/loader/file_loader/unstructured_loader.py
  deepsearcher/loader/splitter.py
  deepsearcher/loader/web_crawler/__init__.py
  deepsearcher/loader/web_crawler/base.py
  deepsearcher/loader/web_crawler/crawl4ai_crawler.py
  deepsearcher/loader/web_crawler/firecrawl_crawler.py
  deepsearcher/loader/web_crawler/jina_crawler.py
  deepsearcher/offline_loading.py
  deepsearcher/online_query.py
  deepsearcher/tools/log.py
  deepsearcher/vector_db/base.py
  deepsearcher/vector_db/milvus.py
  main.py
  pyproject.toml
  setup.py
Labels: approved, lgtm, size/XL

#71 feat: Update README and config for OpenAIEmbedding support; modify requirements
  README.md
  config.yaml
  requirements.txt
Labels: approved, size/M, lgtm

#74 enhance: add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: approved, lgtm, size/L

#75 add claude llm
  README.md
  deepsearcher/llm/__init__.py
  deepsearcher/llm/anthropic_llm.py
Labels: approved, size/M, lgtm

#76 add evaluation module and script
  evaluation/README.md
  evaluation/eval_config.yaml
  evaluation/evaluate.py
  examples/evaluation.py
Labels: approved, lgtm, size/L

#77 rename grok to xai
  README.md
  deepsearcher/llm/__init__.py
  deepsearcher/llm/xai.py
  evaluation/evaluate.py
Labels: approved, lgtm, size/S

#79 Update README.md
  README.md
Labels: approved, lgtm, size/XS

#82 enhance: add Ruff workflow
  .github/workflows/ruff.yml
  Makefile
Labels: approved, lgtm, size/S

#83 feat: add new llm provider PPIO
  README.md
  config.yaml
  deepsearcher/llm/__init__.py
  deepsearcher/llm/ppio.py
  evaluation/eval_config.yaml
Labels: approved, size/M, lgtm

#84 refactor agent module
  deepsearcher/agent/__init__.py
  deepsearcher/agent/base.py
  deepsearcher/agent/chain_of_rag.py
  deepsearcher/agent/collection_router.py
  deepsearcher/agent/deep_search.py
  deepsearcher/agent/naive_rag.py
  deepsearcher/agent/prompt.py
  deepsearcher/agent/rag_router.py
  deepsearcher/agent/reflection.py
  deepsearcher/agent/search_vdb.py
  deepsearcher/agent/sub_query.py
  deepsearcher/agent/summay.py
  deepsearcher/cli.py
  deepsearcher/configuration.py
  deepsearcher/llm/ppio.py
  deepsearcher/online_query.py
Labels: approved, lgtm, size/XXL

#85 add statistics record into evaluation script
  evaluation/evaluate.py
Labels: approved, lgtm, size/S

#86 feat: support using local LLMs via Ollama
  README.md
  config.yaml
  deepsearcher/llm/__init__.py
  deepsearcher/llm/ollama.py
  evaluation/eval_config.yaml
  requirements.txt
Labels: approved, size/M, lgtm

#94 feat: add support for base URL and embedding dimension configuration
  config.yaml
  deepsearcher/embedding/openai_embedding.py
  deepsearcher/llm/openai_llm.py
  examples/basic_example.py
Labels: approved, size/M, lgtm
